openapi: 3.0.0
info:
  title: project name
  version: '1.0'
  contact:
    name: project
    email: email@example.domain.com
  description: An OpenAPI specification
  license:
    name: MIT
    url: ../../LICENSE.md
servers:
  - url: 'http://localhost:3000/api'
tags:
  - name: user
    description: A user of the app
paths: {}
components:
  schemas: {}
